tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: covid19_chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  model: transformer/polyencoder
  model_file: fine_tuning_model/covid19_scraped_ver7/poly_encoder_covid19
  override:
    model: transformer/polyencoder
    no_cuda: True
  no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page
